#!/bin/bash
# borrows from https://gist.github.com/gfrey/8472007 and
# https://github.com/dynport/urknall/blob/master/examples/tpl_haproxy.go#L44.

set -eo pipefail

function starthaproxy {
  haproxy -p $pid_path -f $config_path -D
}

function reloadhaproxy {
  if [[ -s $pid_path ]]; then
    haproxy -p $pid_path -f $config_path -D -sf $(cat $pid_path)
  else
    echo "Pid file $pid_path does't exist or is empty."
  fi
}

pid_path=/var/run/haproxy.pid
config_path=/etc/haproxy/haproxy.cfg
starthaproxy $pid_path $config_path

trap "reloadhaproxy" SIGHUP
trap "exit 0" 2 3 15

while true; do sleep 0.2; done
